package com.banksphere.controller;

import com.banksphere.dto.ApiResponse;
import com.banksphere.dto.branch.BranchResponse;
import com.banksphere.dto.branch.CreateBranchRequest;
import com.banksphere.dto.branch.UpdateBranchStatusRequest;
import com.banksphere.service.BranchService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/branches")
@RequiredArgsConstructor
public class BranchController {

    private final BranchService branchService;

    /**
     * Creates a new branch.
     * The branchCode and IFSC are auto-generated by the service logic.
     */
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
    @PostMapping
    public ApiResponse<BranchResponse> create(@Valid @RequestBody CreateBranchRequest request) {
        BranchResponse created = branchService.createBranch(request);
        return ApiResponse.ok("Branch created successfully", created);
    }

    /**
     * Fetches all branches in the system.
     */
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
    @GetMapping
    public ApiResponse<List<BranchResponse>> list() {
        List<BranchResponse> branches = branchService.getAllBranches();
        return ApiResponse.ok("Branches fetched successfully", branches);
    }

    /**
     * Updates only the status (ACTIVE/INACTIVE) of a specific branch.
     * Path variable 'id' expects a UUID string.
     */
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
    @PatchMapping("/{id}/status")
    public ApiResponse<BranchResponse> updateStatus(
            @PathVariable String id,
            @Valid @RequestBody UpdateBranchStatusRequest request
    ) {
        // We pass the raw string ID and status; the ServiceImpl handles UUID conversion and validation
        BranchResponse updated = branchService.updateBranchStatus(id, request.getStatus());
        return ApiResponse.ok("Branch status updated successfully", updated);
    }
}